# Delete

We are going to see how to delete one or multiple rows of a table based on some filtering criteria

## Imports

In [1]:
import psycopg2
import numpy as np
#import a folder in the parent directory
import sys
sys.path.append('../')
import dbtools.dbtools as qrs
import dbtools.delete as delete
from pathlib import Path
import tifffile as tiff

## Connection

In [2]:
try:
    # Connect to the PostgreSQL database
    conn = qrs.connect()
    print("Connected to the database")

except (Exception, psycopg2.DatabaseError) as error:
    print(error)

Connected to the database

## Loading the table from where we want to delete to check

In [3]:
table_name = 'experiments'

data = qrs.get_data_metadata(table_name)

data

,id_experiment,folder_path_experiment,description_experiment,author_experiment,hyperband_objective_experiment,hyperband_max_epochs_experiment,hyperband_factor_experiment,hyperband_iterations_experiment,hyperband_executions_per_trial_experiment,bayesian_trials_experiment,bayesian_warmup_experiment,bayesian_executions_per_trial_experiment,early_stopping_experiment
0,15,placeholder,A placeholder experiment to test the database ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 10 bayesian found configurations are now t...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 10 bayesian found configurations are now t...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 10 bayesian found configurations are now t...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,29,/host/mnt/nvme2/nases/DataDriven_UT_AlbertoVic...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,25,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 10 bayesian found configurations are now t...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,32,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Hyperband + Bayesian search. The top 10 config...,Alberto Vicente del Egido string,val_loss string,200 string,3 string,5 string,5 string,100 string,5 string,5 string,val_loss with patience of 50 epochs and restor...
10,33,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Hyperband + Bayesian search. The top 10 config...,Alberto Vicente del Egido string,val_loss string,200 string,3 string,5 string,5 string,100 string,5 string,5 string,val_loss with patience of 50 epochs and restor...
11,34,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Hyperband + Bayesian search. The top 10 config...,Alberto Vicente del Egido string,val_loss string,200 string,3 string,5 string,5 string,100 string,5 string,5 string,val_loss with patience of 50 epochs and restor...
12,35,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Hyperband + Bayesian search. The top 10 config...,Alberto Vicente del Egido string,val_loss string,200 string,3 string,5 string,5 string,100 string,5 string,5 string,val_loss with patience of 50 epochs and restor...
13,36,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Hyperband + Bayesian search. The top 10 config...,Alberto Vicente del Egido string,val_loss string,200 string,3 string,5 string,5 string,100 string,5 string,5 string,val_loss with patience of 50 epochs and restor...
14,37,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,38,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,39,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,40,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,41,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,44,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,Top 3 configurations are trained using a KFold...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,val_loss with patience of 50 epochs and restor...
20,46,/home/alberto.vicente/phd/DataDriven_UT_Albert...,Creating baseline models using Juan Ignacios t...,Alberto Vicente del Egido string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Filtering to decide what to delete

We want to delete all the measurements with the metadata key signal_type_measurement as amplitude.

In [ ]:
filtered_data = data[data['folder_path_experiment']== 'Prueba 6']

filtered_data

Empty DataFrame
Columns: [id_material, name_material, layer_thickness_material]
Index: []

## Deleting

In [5]:
delete.delete(conn, table_name, filtered_data['id_material'].values)